import torch
import numpy as np
import json
import warnings
import shap
from lime.lime_text import LimeTextExplainer
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Suppress some noisy warnings for cleaner outputs
warnings.filterwarnings("ignore")

class ExplainableBertPredictor:
    def __init__(self, model_path="distilbert-base-uncased"):
        """
        Initializes the model and tokenizer from an un-tuned or trained checkpoint.
        Automatically sets `output_attentions=True` which is required for custom visualization.
        """
        self.label_names = ["AI", "Networks", "Security", "Systems"]
        self.tokenizer = AutoTokenizer.from_pretrained(model_path)
        
        # Load model and explicitly permit attention output
        self.model = AutoModelForSequenceClassification.from_pretrained(
            model_path,
            num_labels=4,
            problem_type="multi_label_classification",
            output_attentions=True,
            dtype=torch.float16
        )
        
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model.to(self.device)
        self.model.eval()

    def predict_proba(self, texts):
        """
        1. Wrapper function to return probability scores using sigmoid.
        Expected directly by SHAP and LIME Explainers.
        """
        # SHAP/LIME often pass a NumPy array of strings; force conversion to a native python list
        if isinstance(texts, str):
            texts = [texts]
        elif isinstance(texts, np.ndarray):
            texts = texts.tolist()
        else:
            texts = list(texts)
            
        inputs = self.tokenizer(
            texts, 
            padding=True, 
            truncation=True, 
            max_length=256, 
            return_tensors="pt"
        )
        
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        
        with torch.no_grad():
            outputs = self.model(**inputs)
            logits = outputs.logits
            
        probs = torch.sigmoid(logits).cpu().numpy()
        return probs

    def explain_lime(self, text, label_idx, num_features=5):
        """
        2. Local Explanation using LimeTextExplainer.
        Identifies words that pushed the prediction locally toward the target label index.
        """
        explainer = LimeTextExplainer(class_names=self.label_names)
        
        # `labels=[label_idx]` isolates LIME specifically to that class probability dimension
        exp = explainer.explain_instance(
            text, 
            self.predict_proba, 
            labels=[label_idx], 
            num_features=num_features,
            num_samples=100  # Kept lower for faster runtime; increase to 500+ for stable inference
        )
        
        # Filter for strictly positive/contributing features to match user request
        lime_words = [word for word, weight in exp.as_list(label=label_idx) if weight > 0]
        return lime_words

    def explain_shap(self, text, label_idx, max_words=5):
        """
        3. Global + Local Explanation using shap.Explainer
        Sorts the SHAP attribution values generated by sequentially masking the input string.
        """
        masker = shap.maskers.Text(self.tokenizer)
        explainer = shap.Explainer(self.predict_proba, masker, output_names=self.label_names)
        
        shap_values = explainer([text])
        
        # Isolated SHAP values mapped exactly to the current label dimension
        label_shap_values = shap_values[..., label_idx].values[0]
        tokens = shap_values.data[0]
        
        # Capture strictly positive contributions
        word_contributions = []
        for j in range(len(tokens)):
            if label_shap_values[j] > 0:
                word_contributions.append((str(tokens[j]).strip(), label_shap_values[j]))
        
        # Descending sort by contribution weight
        word_contributions = sorted(word_contributions, key=lambda x: x[1], reverse=True)
        
        shap_words = []
        for w, _ in word_contributions:
            if w and w not in shap_words:
                shap_words.append(w)
                if len(shap_words) == max_words:
                    break
                    
        return shap_words

    def explain_attention(self, text, max_words=5):
        """
        4. Attention Visualization.
        Fetches internal attention weights, aggressively pooling over Multi-Heads and Layers
        to capture the macroscopic understanding from the [CLS] sequence header.
        """
        inputs = self.tokenizer(
            text, 
            return_tensors="pt", 
            add_special_tokens=True, 
            max_length=256, 
            truncation=True
        )
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        
        with torch.no_grad():
            outputs = self.model(**inputs, output_attentions=True)
            attentions = outputs.attentions
            
        # attentions: tuple(12 layers) of tensors shape [batch, num_heads, seq_len, seq_len]
        # Pool all layers and heads to get [batch, seq_len, seq_len]
        all_layer_attention = torch.stack(attentions) 
        mean_attention = all_layer_attention.mean(dim=0).mean(dim=1) 
        
        # Isolate the mapping from [CLS] to all individual sequence tokens
        cls_attention = mean_attention[0, 0, :].cpu().numpy()
        
        input_ids = inputs["input_ids"][0]
        tokens = self.tokenizer.convert_ids_to_tokens(input_ids)
        
        # Sort indices iteratively for highest attention signals
        top_indices = np.argsort(cls_attention)[::-1]
        
        attention_words = []
        for idx in top_indices:
            token = tokens[idx]
            # Strip subword tokens and special characters to deliver raw text words
            if token not in ['[CLS]', '[SEP]', '[PAD]'] and not token.startswith("##"):
                if token not in attention_words:
                    attention_words.append(token)
                if len(attention_words) == max_words:
                    break
                    
        return attention_words

    def explain_all(self, text, threshold=0.5):
        """
        5. Final Pipeline combining predictions alongside all three explainability frameworks.
        Output adheres strictly to the required payload framework.
        """
        probs = self.predict_proba([text])[0]
        
        # Attention is calculated from the CLS token global field 
        attention_words = self.explain_attention(text)
        
        explanations = []
        for idx, prob in enumerate(probs):
            if prob >= threshold:
                label_name = self.label_names[idx]
                
                # Fetch localized interpretability metrics
                lime_words = self.explain_lime(text, idx)
                shap_words = self.explain_shap(text, idx)
                
                # Strict structure configuration
                explanations.append({
                    "label": label_name,
                    "confidence": round(float(prob), 4),
                    "why": {
                        "lime_words": lime_words,
                        "shap_words": shap_words,
                        "attention_words": attention_words
                    }
                })
                
        return explanations

if __name__ == "__main__":
    import os
    print("Instantiating Explainable BERT...")
    model_path = os.path.join(os.path.dirname(__file__), "..", "bert-multi-label-model", "final")
    explainer = ExplainableBertPredictor(model_path)
    
    sample_text = "The neural network was trained on routing protocols to prevent encryption attacks on the distributed system."
    print(f"\nEvaluating Context: '{sample_text}'")
    
    result = explainer.explain_all(sample_text, threshold=0.4)
    
    print("\n[Generated Explainability Payload]")
    print(json.dumps(result, indent=2))
